# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            FM-4 
tagline:          
description:      
url:              https://frankiem-4.github.io
baseurl:          /

author:
  name:           'Frankie McDonough IV'
  url:            

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/frankiem-4
